# Generated by Django 3.2.2 on 2021-05-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
    ]
